### ISSUE TITLE
Replace the file based logger

### ISSUE THREAD

**Issue by juanbono** [lambdaclass/libtorrent-rs#17]
Right now the project uses a file-based logger. 
Consider using the [tracing](https://crates.io/crates/tracing) crate and writing to standard error instead of writing to a file.
You also need to remove the configuration parameter for the logger.
Check that it can log using async.

**Comment by a-moreira** [comment]
hey @juanbono, I started working on this here https://github.com/lambdaclass/libtorrent-rs/pull/24, is that what you were expecting? :-)
